### ISSUE TITLE
Speed up iree_tests for large remote files by adding a caching layer on CI machines

### ISSUE THREAD

**Issue by ScottTodd** [nod-ai/SHARK-TestSuite#169]
This repo on its own has this directory structure:

```
SHARK-TestSuite/
  iree_tests/
    conftest.py
    onnx/
    pytorch/
      models/
        opt-125M/
          inference_input.0.bin
          model.mlirbc
          real_weights_data_flags.txt
        resnet50/
          model.mlirbc
```

The .bin and .mlirbc files are large enough that many are stored remotely (e.g. on Azure). For CI machines, we want those files to be cached locally so jobs don't need to redownload them every run (using bandwidth and taking 20+ minutes).

Caching can be tricky, so let's try to start simple and add features as needed. There may be an off the shelf caching layer or tool we can use if it gets to that point.

Brainstorming a few approaches:

1. Maintain a parallel directory structure in `~/iree_tests_cache/`:

    ```
    pytorch/
      models/
        opt-125M/
          inference_input.0.bin
    ```

    Run pytest from the test repo, redirecting test flagfile paths using an environment variable:

    ```diff
    - --input=1x8xi64=@inference_input.0.bin
    + --input=1x8xi64=@${IREE_TESTS_ROOT}/pytorch/models/opt-125M/inference_input.0.bin
    ```

    with that environment variable defaulting to the repository path itself and set to the cache dir on CI machines.

    That may not be portable across systems (Windows may want `%IREE_TESTS_ROOT%/`?).

2. Maintain a parallel directory with cached files, copy the test repo over it, then run pytest _from the cache dir_.

    This would pollute the cache with other files but would require minimal configuration changes and file move operations.

3. Maintain a parallel directory with cached files, copy files from the cache directory into the test repo, then run pytest _from the repo_.

    This would keep the cache clean, but would involve copying more files on the local disk (machines would then have two copies of large files)

4. Same as 3, but with symlinks. Maybe add a `setup_cache_symlinks.py` script to help? Could also look at overlay file systems / symlink trees (https://unix.stackexchange.com/a/179404) 

---

* All of these approaches need a way to initially populate and then update the cache.
* Ideally the test runner itself wouldn't need to know about caching at all. I'd prefer symlinking or copying files over adding new environment variables for that reason.

**Comment by saienduri** [comment]
Nice writeup! So, the solution I have combines a couple of these things. First, we use an environment variable passed in (IREE_TEST_FILES) to determine if we even want to use a cache or not (don't want to make it a requirement). In CI, we set this because we want a persistent runner cache. If this is set, we download files to the cache location specified and symlink it to the testing directory. Otherwise, we just directly download into the repo, and it won't be using any caching mechanism. The test runner doesn't need to know about caching at all, and even initially, it will just create the cache and download there if it doesn't exist. There is no manual interaction that needs to take place for any system or person that wants to use this.

**Comment by saienduri** [comment]
PR coming soon :)
